services:
  mysql:
    image: mysql
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./fabrica.sql:/docker-entrypoint-initdb.d/fabrica.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
volumes:
  mysql_data:
