services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./fabrica.sql:/docker-entrypoint-initdb.d/fabrica.sql
volumes:
  mysql_data:
